name: "rotas-compose-service-dev"

services:
    dev-frontend:
        build:
            context: ./src/frontend/
            dockerfile: Dockerfile
            args:
                ANGULAR_ENVIRONMENT: "Development"
        networks:
            - "calculo-rotas-network-dev"
        ports:
            - "4998:80"
        depends_on:
            - dev-backend-api
        
    dev-backend-api:
        build:
            context: ./src/backend/
            dockerfile: Dockerfile
            args:
                PORT: 4999
                ASPNETCORE_ENVIRONMENT: "Development"
        ports:
            - "4999:4999"
        networks:
            - "calculo-rotas-network-dev"
    
networks:
    "calculo-rotas-network-dev":
        driver: bridge
